version: "3.7"

services:
  alphaz:
      build:
        context: https://github.com/AftahBagas/AlphaZ-Plugins.git#alpha
      depends_on:
        - mongo
      restart: on-failure
      environment:
          DATABASE_URL: mongodb://root:example@mongo
      env_file:
        - config.env

  mongo:
      image: mongo
      volumes:
        - mongo_alphaz:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_alphaz:
